name: urban-morphology
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas   >=0.14 
  - momepy      >=0.6.0     # Core library for urban form metrics
  - osmnx       >=1.3.0     # For downloading and analyzing OSM street data
  - shapely
  - fiona
  - pyproj
  - contextily  >=1.3.0     # For basemaps
  - matplotlib  >=3.8       # For plotting
  - seaborn
  - pandas
  - numpy
  - networkx                # Underlying graph analysis
  - jupyterlab
  - rtree
  - dash
  - dash_table
  - plotly
  - ipython
  - pip